name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Use variables
        run: |
          echo "vars variable : ${{ vars }}"
          echo "env variable : ${{ env }}"
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.nuc_cluster.REGISTRY_ADDRESS }}
          username: ${{ env.nuc_cluster.REGISTRY_USER }}
          password: ${{ env.nuc_cluster.REGISTRY_PASS }}
