name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY_ADDRESS }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ vars.REGISTRY_PASS }}
      - name: Build Image
        run: |
          echo "${{ vars.REGISTRY_ADDRESS }}/${{ vars.REGISTRY_BUCKET }}/canary-deployment-producer:commitid"
          echo "docker build -t ${{ vars.REGISTRY_ADDRESS }}/${{ vars.REGISTRY_BUCKET }}/canary-deployment-producer:commitid ."
          echo "env variable : ${{ toJson(env) }}"
