name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Use variables
        run: |
          echo "vars variable : ${{ toJson(vars) }}"
          echo "env variable : ${{ toJson(env) }}"
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY_ADDRESS }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ vars.REGISTRY_PASS }}
