name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY_ADDRESS }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ vars.REGISTRY_PASS }}
      -
        name: Build Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.REGISTRY_ADDRESS }}/${{ vars.REGISTRY_BUCKET }}/canary-deployment-producer:latest
